### ISSUE TITLE
MacOS Catalina 10.15.4 stucked at "[installapplications] waiting for user script to complete: /Library/installapplication/user-scripts/depnotify_user_launcher.py""

### ISSUE THREAD

**Issue by windliyue** [erikng/installapplicationsdemo#4]

**Comment by SilentHunter124** [comment]
I think you exchanged the DEPNotify Package with different one, as it opens a specific UBER entrypoint. Just execute this python script manually and see what the exact problem is.

**Comment by erikng** [comment]
Probably addressed with: https://github.com/erikng/installapplicationsdemo/commit/8d7f6dcb4e77f926d3c7c8d9299442bd65c5cb2b
